version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: twitter-client # specify the directory of the Dockerfile
    ports:
      - "1234:1234" # specify port forewarding

  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
